# UFW Firewall Configuration Example
# This configuration uses UFW (Uncomplicated Firewall) as the backend

log_files:
- path: /var/log/auth.log
  patterns:
  - ban_time: 1h
    ip_group: 1
    regex: Failed password for .* from (\d+\.\d+\.\d+\.\d+)
    threshold: 3
  - ban_time: 2h
    ip_group: 1
    regex: Invalid user .* from (\d+\.\d+\.\d+\.\d+)
    threshold: 5

- path: /var/log/nginx/access.log
  patterns:
  - ban_time: 1h
    ip_group: 1
    regex: (\d+\.\d+\.\d+\.\d+) .* "[^"]*" 401
    threshold: 5

production_mode: true
web:
  enabled: true
  port: 8080

# UFW Firewall Configuration
firewall:
  type: ufw
  whitelist: []             # Additional firewall-specific whitelist

# Global whitelist (applies to all firewall types)
whitelist:
- 127.0.0.1
- ::1
- 192.168.1.0/24